name: Build master

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - id: var
      name: Setup variables
      run: echo ::set-output name=commit_hash::${GITHUB_SHA:0:7}
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Use gradle cache for faster builds
      uses: actions/cache@v4
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
    - name: Build with Gradle
      run: ./gradlew build
      env:
        MI_VERSION: 0.0.0-git-${{ steps.var.outputs.commit_hash }}
    - name: Gametest Server
      run: |
        ./gradlew runGameTestServer
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Modern Industrialization ${{ steps.var.outputs.commit_hash }}
        path: build/libs
